config/routes.rb
MattApp::Application.routes.draw do
  devise_for :users
  resources :posts

  get "static_pages/home"
  get "static_pages/help"
  get "static_pages/about"
  get "static_pages/contact"
  get "static_pages/portfolio"

  root 'static_pages#home'

end

app/models/post.rb
class Post < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable

        def self.find_or_create_form_auth_hash(auth_hash)
        	(find_by_auth_hash_auth_hash) || create_from_auth_hash(auth_hash)
		end

		def self.find_by_auth_hash(auth_hash)
			where(
				provider: auth_hash.provider,
				uid: auth_hash.uid
			).first
		end
		def self.create_from_auth_hash(auth_hash)
			create(
				provider: auth_hash.provider,
				uid: auth_hash.uid,
				email: auth_hash.info.email,
				name: auth_hash.info.name,
				oauth_token: auth_hash.credentials.token,
				oauth_expires_at: Time.at(auth_hash.credentials.expires_at)
				)
		end
		def password_required?
			super & prvider.blank?
		end
		def update_with_password(params, *options)
			if encrypted_password.blank?
				update_attributes(params, *options)
			else
				super
			end
		end
	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render action: 'show', status: :created, location: @post }
      else
        format.html { render action: 'new' }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :content)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end

  def contact
  end

  def portfolio
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Matt's App", root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">      
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "All Posts", posts_path %></li>
        <li><%= link_to "New Post", new_post_path %></li>

        <% if user_signed_in? %>
          <li><%= link_to "Settings", edit_user_registration_path %></li>
          <li><%= link_to "logout", destroy_user_session_path, method: :delete %></li>
          <% else %>
          <li><%= link_to "login", new_user_session_path %></li>
          <li><%= link_to "Sign Up", new_user_registration_path %></li>
        <% end %>

      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</div><!-- /.container -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MattApp</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <script>
  window.fbAsyncInit = function() {
    FB.init({
      appId      : '875475019138011',
      xfbml      : true,
      version    : 'v2.2'
    });
  };

  (function(d, s, id){
     var js, fjs = d.getElementsByTagName(s)[0];
     if (d.getElementById(id)) {return;}
     js = d.createElement(s); js.id = id;
     js.src = "//connect.facebook.net/en_US/sdk.js";
     fjs.parentNode.insertBefore(js, fjs);
   }(document, 'script', 'facebook-jssdk'));
</script>
</head>
<body>
	<% flash.each do |name, msg| %>
	<div class="alert text-center alert-<%= name == notice ? "success" : "error" %>">
	<% end %>
<%= render"layouts/header" %>
       <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>
<%= yield %>

</body>
</html>

app/views/posts/_form.html.erb
<%= simple_form_for(@post, html: {class: 'form-horizontal' }) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :title %>
    <%= f.input :content %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<div class="container">
	<h1>Editing post</h1>
	<%= render 'form' %>
	<%= link_to 'Show', @post %> |
	<%= link_to 'Back', posts_path %>
</div>

app/views/posts/index.html.erb
<div class="container">
  <h1>Listing posts</h1>
  <table class="table">
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= post.content %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody></table>
  <br>
  <%= link_to 'New Post', new_post_path, class: "btn btn-primary btn-lg" %>
</div>

app/views/posts/new.html.erb
<div class="container">
	<h1>New post</h1>

	<%= render 'form' %>

	<%= link_to 'Back', posts_path %>
</div>

app/views/posts/show.html.erb
<div class="container">
	<p id="notice"><%= notice %></p>
	<p>
		<strong>Title:</strong>
		<%= @post.title %>
	</p>
	<p>
		<strong>Content:</strong>
		<%= @post.content %>
	</p>

	<%= link_to 'Edit', edit_post_path(@post) %> |
	<%= link_to 'Back', posts_path %>
</div>

app/views/static_pages/about.html.erb
<h1>StaticPages#about</h1>
<p>Find me in app/views/static_pages/about.html.erb</p>

app/views/static_pages/contact.html.erb
<h1>StaticPages#contact</h1>
<p>Find me in app/views/static_pages/contact.html.erb</p>

app/views/static_pages/help.html.erb
<h1>StaticPages#help</h1>
<p>Find me in app/views/static_pages/help.html.erb</p>

app/views/static_pages/home.html.erb
<div class="jumbotron">
	<div class="container">
		<h1>Matt's App</h1>
		<p>
			Welcome to the App
		</p>
		<div
  class="fb-like"
  data-share="true"
  data-width="450"
  data-show-faces="true">
</div>
		<div class="progress">
			<div class="progress-bar" style="width: 40%;"></div>
			<div class="progress-bar progress-bar-warming" style="width: 10%;"></div>
			<div class="progress-bar progress-bar-danger" style="width: 10%;"></div>
			<div class="progress-bar progress-bar-success" style="width: 10%;"></div>
			<div class="progress-bar progress-bar-info" style="width: 30%;"></div>
		</div>
	</div>
</div>
<div class="container">
	<div class="row">
		<div class="col-md-12">
			<h3>How it works</h3>
		</div>
	</div>
	<div class="row">
		<div class="col-md-4">
			<h2>Connect with Facebook</h2>
			<p>Signup or login to this app with your facebook account</p>
		</div>
		<div class="col-md-4">
			<h2>Create fun posts</h2>
			<p>Start posting cool content. Max 160 characters twitter style</p>
		</div>
		<div class="col-md-4">
			<h2>Share them</h2>
			<p>Share them with your friends on facebook</p>
		</div>
	</div>
</div>

app/views/static_pages/portfolio.html.erb
<h1>StaticPages#portfolio</h1>
<p>Find me in app/views/static_pages/portfolio.html.erb</p>